export const TOGGLE_STATUS = 'TOGGLE_STATUS';
export const UPDATE_TIMER  = 'UPDATE_TIMER';
export const UPDATE_TIMERCOUNTER  = 'UPDATE_TIMERCOUNTER';
export const RESET_TIMERCOUNTER  = 'RESET_TIMERCOUNTER';
